name: Testing flugel test.
on:
  [push]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{TF_VAR_secret_key}}
      AWS_ACCESS_KEY_ID: ${{TF_VAR_access_key}}
      AWS_DEFAULT_REGION: ${{TF_VAR_region}}


    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Go'
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: 'Setup SSH Key'
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: 'Setup Dependencies'
        working-directory: test/
        run: go get -v -t -d && go mod tidy

      - name: 'Lets test the test'
        working-directory: test/
        run: go test -v
